# This is a basic workflow to help you get started with Actions

name: Hello world exercicio 1

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job1:
    name: Primeiro Job
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: env | sort
        
  job2:
    name: Segundo Job
    runs-on: windows-latest
    steps:
      - name: Passo 2
        run: "Get-ChildItem Env: | Sort-Object Name"
        
  job3:
    name: Terceiro Job
    runs-on: macos-latest
    steps:
      - name: Passo 3
        run: echo Passo final
 
job4:
    name: Quarto Job
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    
    steps:
      - name: Ultimo passo
        run: date

